version: 2

updates:
  # Python dependencies
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  open-pull-requests-limit: 5
  labels:
  - "dependencies"
  - "python"
  commit-message:
    prefix: "deps"
    include: "scope"
    # Group minor and patch updates together
  groups:
    python-dependencies:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"

  # GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  open-pull-requests-limit: 3
  labels:
  - "dependencies"
  - "github-actions"
  commit-message:
    prefix: "ci"
    include: "scope"
