INPUT_XMLS = {
    "aemo-2024-green": "/Users/meas/Library/CloudStorage/GoogleDrive-measrainsey.meng@openenergytransition.org/Shared drives/OET Shared Drive/Projects/[008] ENTSOE - Open TYNDP I/2 - interim deliverables (working files)/Plexos Converter/Input Models/AEMO/2024 ISP/2024 ISP Green Energy Exports/2024 ISP Green Energy Exports Model.xml",
    "aemo-2024-isp-progressive": "/Users/meas/Library/CloudStorage/GoogleDrive-measrainsey.meng@openenergytransition.org/Shared drives/OET Shared Drive/Projects/[008] ENTSOE - Open TYNDP I/2 - interim deliverables (working files)/Plexos Converter/Input Models/AEMO/2024 ISP/2024 ISP Progressive Change/2024 ISP Progressive Change Model.xml",
    "aemo-2024-isp-step": "/Users/meas/Library/CloudStorage/GoogleDrive-measrainsey.meng@openenergytransition.org/Shared drives/OET Shared Drive/Projects/[008] ENTSOE - Open TYNDP I/2 - interim deliverables (working files)/Plexos Converter/Input Models/AEMO/2024 ISP/2024 ISP Step Change/2024 ISP Step Change Model.xml",
    "caiso-irp23": "/Users/meas/Library/CloudStorage/GoogleDrive-measrainsey.meng@openenergytransition.org/Shared drives/OET Shared Drive/Projects/[008] ENTSOE - Open TYNDP I/2 - interim deliverables (working files)/Plexos Converter/Input Models/CAISO/IRP/IRP23 - 25MMT Stochastic models with CEC 2023 IEPR Load Forecast/caiso-irp23-stochastic-2024-0517/CAISOIRP23Stochastic 20240517.xml",
    "caiso-sa25": "/Users/meas/Library/CloudStorage/GoogleDrive-measrainsey.meng@openenergytransition.org/Shared drives/OET Shared Drive/Projects/[008] ENTSOE - Open TYNDP I/2 - interim deliverables (working files)/Plexos Converter/Input Models/CAISO/Seasonal Assessments/2025-summer-loads-and-resources-assessment-public-stochastic-model/CAISOSA25 20250505.xml",
    "nrel-118": "/Users/meas/Library/CloudStorage/GoogleDrive-measrainsey.meng@openenergytransition.org/Shared drives/OET Shared Drive/Projects/[008] ENTSOE - Open TYNDP I/2 - interim deliverables (working files)/Plexos Converter/Input Models/NREL/NREL-118/mti-118-mt-da-rt-reserves-all-generators.xml",
    "sem-2024-2032": "/Users/meas/Library/CloudStorage/GoogleDrive-measrainsey.meng@openenergytransition.org/Shared drives/OET Shared Drive/Projects/[008] ENTSOE - Open TYNDP I/2 - interim deliverables (working files)/Plexos Converter/Input Models/SEM/SEM 2024-2032/PUBLIC Validation 2024-2032 Model 2025-03-14.xml",
    "marei-eu": "/Users/meas/Library/CloudStorage/GoogleDrive-measrainsey.meng@openenergytransition.org/Shared drives/OET Shared Drive/Projects/[008] ENTSOE - Open TYNDP I/2 - interim deliverables (working files)/Plexos Converter/Input Models/University College Cork/MaREI/EU Power & Gas Model/European Integrated Power & Gas Model.xml",
    "plexos-world-2015": "/Users/meas/Library/CloudStorage/GoogleDrive-measrainsey.meng@openenergytransition.org/Shared drives/OET Shared Drive/Projects/[008] ENTSOE - Open TYNDP I/2 - interim deliverables (working files)/Plexos Converter/Input Models/University College Cork/PLEXOS-World 2015/dataverse_files/PLEXOS-World 2015 Gold V1.1.xml",
}
