name: Dependency Review

on:
  pull_request:
    branches: [main]

# This workflow scans pull requests for dependency changes and checks for known vulnerabilities
# Only runs on PRs to prevent unnecessary runs on direct pushes

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Scan Dependencies for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
          # Fail the build if vulnerabilities are found at this severity or higher
        fail-on-severity: moderate
          # Comment on the PR with details
        comment-summary-in-pr: always
          # Deny licenses (optional - add licenses you want to block)
          # deny-licenses: GPL-3.0, AGPL-3.0
